# Generated by Django 5.0 on 2024-02-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0002_student_age_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
    ]
