# Generated by Django 5.0 on 2024-02-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0005_statusupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='course',
        ),
    ]
